# Generated by Django 4.2.9 on 2024-02-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nausea', models.IntegerField()),
                ('headache', models.IntegerField()),
                ('bellyache', models.IntegerField()),
            ],
        ),
    ]
