# Generated by Django 4.2.9 on 2024-02-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0002_remove_effect_disease_effect_symptom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='effect',
            old_name='drug',
            new_name='item',
        ),
    ]
