# Generated by Django 4.2.9 on 2024-02-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='disease',
        ),
        migrations.AlterField(
            model_name='symptom',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
