# Generated by Django 4.2.9 on 2024-02-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0002_remove_symptom_disease_alter_symptom_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='value',
            new_name='name',
        ),
    ]
